### ISSUE TITLE
使用后发现几个问题

### ISSUE THREAD

**Issue by mofomake** [IronKinoko/agefans-enhance#11]
视频加载错乱，比如播放A的8集，点击第9集时播放的却是B的3集，第10集又是C的某一集，或者干脆加载错误。

获取视频链接偶尔是加载错误，重试。 然后重试后也因上面的问题获取错误的链接。

这是我使用后发现的两个问题。

**Comment by IronKinoko** [comment]
能提供下 A或B 的链接下，让我复现一下
加载错误，重试  这个其实是agefans的问题，有时候就是会获取失败，目前没找到怎么应对

**Comment by mofomake** [comment]
> 能不能提供下A或B的链接，让我复现一下吗？
> 加载，重试其实是粉丝的问题，错误会是获取失败，目前没找到怎么解决

我不知道能不能复现成功，我试过几次，开始会大量出现，多次刷新网页后就基本没出现了，具体链接为https://www.agefans.cc/play/20120040(魔笛)随便点的几集，跳转到‘非枪人生’中的某一集

**Comment by IronKinoko** [comment]
感谢反馈🙏
因为agefans的安全机制，之前没有管他的cookie，导致过期了，获取到的数据都是错的
更新下最新版本(v1.6.7)，如果还有错误再和我说下。
