### ISSUE TITLE
播放器显示加载失败

### ISSUE THREAD

**Issue by gqcdm** [IronKinoko/agefans-enhance#14]
见面5秒开始战斗![image](https://user-images.githubusercontent.com/78142321/131626521-35d3dcca-4352-4f2f-8880-9146b6823719.png)

**Comment by gqcdm** [comment]
链接似乎换成了oss，下载并不带格式后缀
![image](https://user-images.githubusercontent.com/78142321/131626696-151b0daa-11ae-40e9-8d9e-8c3496834f5e.png)
![image](https://user-images.githubusercontent.com/78142321/131626725-7df3236e-60ea-4fea-bb93-cfe41434229c.png)

**Comment by IronKinoko** [comment]
你可以试试关闭脚本后能否正常播放，如果播放不了那就是视频本身的问题。

另外，agefans所有的视频都是第三方cdn链接，因为网络安全限制导致不能直接下载带名字的文件，右键另存为也带不上名字

**Comment by gqcdm** [comment]
> 你可以玩游戏，关闭脚本后可以正常播放，播放不了视频的问题。
> 
> 另外，年龄粉丝所有的视频都看过，因为网络安全限制导致不能直接下载名字的文件，不能保存为也带不上名字

**Comment by gqcdm** [comment]
是可以正常播放的，估计官方的默认加了文件类型

**Comment by IronKinoko** [comment]
感谢反馈，我晚上看看

**Comment by IronKinoko** [comment]
修复了，更新下最新版本（v1.8.8）
