### ISSUE TITLE
我又来issue啦

### ISSUE THREAD

**Issue by gqcdm** [IronKinoko/agefans-enhance#16]
https://www.agefans.cc/play/20210158?playid=2_6 部分视频还是不行

**Comment by IronKinoko** [comment]
没见过的形式，我先研究下😄

**Comment by IronKinoko** [comment]
好了，更新下（1.9.0）

**Comment by gqcdm** [comment]
https://www.agefans.cc/play/20210158?playid=4_6这个播放也不行

**Comment by IronKinoko** [comment]
这个就算不用脚本也播放不了，应该是链接本身的问题吧
