### ISSUE TITLE
如何禁止自动连播？

### ISSUE THREAD

**Issue by rcyggdra** [IronKinoko/agefans-enhance#17]
如何禁止播放完该集后自动跳到下一集？
我需要的是播放完该集后暂停播放；或许能否增加开关？

**Comment by IronKinoko** [comment]
好的，周末会提供开关

2021-09-24 14:17 GMT+08:00, rcyggdra ***@***.***>:

**Comment by rcyggdra** [comment]
感谢作者的更新维护。
