### ISSUE TITLE
请求功能：音量记忆

### ISSUE THREAD

**Issue by rcyggdra** [IronKinoko/agefans-enhance#18]
晚上需要调节音量，切换视频的时候音量又恢复，弄得人一惊一乍……

**Comment by IronKinoko** [comment]
感谢你的意见 ！很快会加上的


rcyggdra ***@***.***> 于2021年11月8日周一 下午4:57写道：

**Comment by IronKinoko** [comment]
好了，更新下就行（v1.13.0)
