### ISSUE TITLE
播放器显示加载失败

### ISSUE THREAD

**Issue by jonm58** [IronKinoko/agefans-enhance#22]
自称贤者弟子的贤者
![图片](https://user-images.githubusercontent.com/73036321/151368870-e700fbc1-6fdf-400d-9678-f5b2118f5245.png)

**Comment by IronKinoko** [comment]
我看都正常的，把链接发出来

**Comment by jonm58** [comment]
用浏览器打开DOH出的问题，emm......

**Comment by jonm58** [comment]
https://www.agemys.com/play/20210155?playid=2_2
发错了，就这页有问题。

**Comment by IronKinoko** [comment]
属于资源问题

我是用age自己的播放器，也有概率放不出来，他的资源有问题
有时会出现401无授权的情况
