### ISSUE TITLE
能出个截图功能不

### ISSUE THREAD

**Issue by Naileon** [IronKinoko/agefans-enhance#23]
# 文字描述

# 网址链接
https://www.agemys.com/play/20200169?playid=2_3

# 视频链接
blob:https://www.agemys.com/3c265598-13af-4daa-a0ed-605ce3c1fdb2

# 环境
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36
脚本版本: 1.14.2

**Comment by IronKinoko** [comment]
你用键盘上的截图键不就好了

**Comment by IronKinoko** [comment]
加好了，更新到最新版本就行(v1.18.0)
