### ISSUE TITLE
历史记录无法更新🐛[Bug]

### ISSUE THREAD

**Issue by xjf555** [IronKinoko/agefans-enhance#24]
### Bug 网页链接

https://www.agemys.com/update

### 简要描述下问题

历史记录页面刷新时会跳到【 最近更新】的界面 ， 且 【 历史】 界面停在了几天前

**Comment by IronKinoko** [comment]
1. 历史记录页面刷新时会跳到【 最近更新】的界面
这个姑且是正常情况，近期也没打算优化。问题不大

2. 【 历史】 界面停在了几天前
你是哪个版本的脚本？更新到最新版本看看。
如果还是不行，就先**删除**脚本，然后**重新安装**。（执行这个操作可能会丢失历史记录）

**Comment by xjf555** [comment]
重新安装，降级都试过了，是最新版的

**Comment by xjf555** [comment]
e（前面我表述的有问题）是在浏览【历史记录】的时候刷新界面会跳到【最近更新】

**Comment by xjf555** [comment]
不明白为什么这个界面会吞掉我的一些字……

**Comment by IronKinoko** [comment]
好的，感谢反馈！！！！！！
我知道问题在哪里了，我会在今天内修复脚本

**Comment by IronKinoko** [comment]
修复了，更新到最新即可（v1.18.4）

**Comment by xjf555** [comment]
ok，问题解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月9日(周三) 下午3:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IronKinoko/agefans-enhance] 历史记录无法更新🐛[Bug] (Issue #24)




 
修复了，更新到最新即可（v1.18.4）
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
