### ISSUE TITLE
推荐适配网站

### ISSUE THREAD

**Issue by ZhReimu** [IronKinoko/agefans-enhance#25]
这个和 `age` 简直是一个模板, 就是播放器不同, 部分 `age` 看不了的这里能看, 它的播放器是 仿 bilibili 的, 感觉还是 `plyr` 好看
http://www.ntyou.cc/

`age` 的部分片源就是来自于这里, 这个网站的播放器属实拉跨。 一样的, 部分 `age` 看不了的这里能看
https://www.dm233.org/
https://www.dm233.tv/

这个网站需要科学上网, 但片源都挺好的, 也是使用的 `plyr` 作为播放器, 但功能启用得太少了
https://www.olevod.com/

**Comment by IronKinoko** [comment]
感谢推荐，近期会适配的
