### ISSUE TITLE
可以加个转译吗？

### ISSUE THREAD

**Issue by darkflame0** [IronKinoko/agefans-enhance#27]
### Bug 网页链接

www.agemys.com

### 简要描述下问题

看了一下，1.20之后换成ts了，使用了很多新语法导致部分版本比较旧的浏览器无法使用了（例如QQ浏览器），可以加个转译兼容旧版本浏览器吗？

**Comment by IronKinoko** [comment]
兼容性调整到 es2017 了，从 caniuse 上看最新版本的 QQ浏览器 可以使用。你先试试吧

**Comment by darkflame0** [comment]
可以了~
