### ISSUE TITLE
🚀[enhancement]可以弄个设置自定义跳过片头的时间吗

### ISSUE THREAD

**Issue by uzcool** [IronKinoko/agefans-enhance#28]
### Bug 网页链接

http://www.yinghuacd.com/

### 简要描述下问题

动漫片头时长不一样  能自定义跳过的时长吗..

**Comment by IronKinoko** [comment]
是有考虑过做这个功能
但实际用起来的时候还得每个番剧填一下跳过时间
个人感觉还是猛按 → 更方便些

这个我再考虑下吧
