### ISSUE TITLE
添加弹弹play弹幕功能

### ISSUE THREAD

**Issue by eventhorizonsky** [IronKinoko/agefans-enhance#29]
### 简要描述下需要的功能、意见或建议

完成这个需求似乎还是需要更换播放器来支持，不知道能不能做成选项的形式。
我用dplayer暂时实现了这个功能，但是因为不熟悉js和本项目的结构，所以是在脚本编辑页现改的（可能比较乱），弹幕接口是我用java写了一个转换弹弹play弹幕json格式的接口放在我服务器上的，应该有更方便的解决方式。
下面的链接是我魔改的脚本，可以看看效果
https://pan.ezsky.games/api/v3/file/source/1747/agemys%20Enhance%20%282%29.user.js?sign=Kgf9dhdhxhjnd1Y8B3WE5JekUWBgoXQJMtXg0FxH-Y8%3D%3A0

**Comment by IronKinoko** [comment]
感谢贡献

我有空会研究下你改动的内容

如果涉及到自架设服务，那只能放弃了

**Comment by eventhorizonsky** [comment]
弹弹提供了开放的弹幕api，可以自由调用的，可以查看
https://api.acplay.net/swagger/ui/index#/
这个文档，我是因为dplayer所需的弹幕json格式和弹弹官方提供的格式不一样所以才写了个接口（因为对js不熟悉的缘故），如果js可以做到这一点应该是不需要再架设服务端的。
dplayer所需的json格式是形如{"code":0,"data":[[弹幕时间,弹幕位置,32位整数表示的颜色,"","弹幕内容"]...]}
弹弹play提供的json格式是形如{"count":21,"comments":[{"cid":编号,"p":"弹幕出现时间,弹幕位置,32位整数表示的颜色,用户ID","m":"弹幕内容"}...]}
只需要转换一下是可以很方便地使用的
