### ISSUE TITLE
几点改进建议

### ISSUE THREAD

**Issue by racedeyu** [IronKinoko/agefans-enhance#3]
首先，谢谢做了一个方便的用户脚本，现在在age终于不用手工跳P了，个人有几个不成熟的建议，希望考虑。再次感谢~

1. 目前播放器按空格为全屏切换，原站的播放器空格为暂停；
2. 全屏播放跳P后不会再次全屏；
3. 原站视频有时会加载失败的，需要刷新一下，希望可以自动刷新；

**Comment by IronKinoko** [comment]
感谢使用， 我会看看你提的这些bug，并且尽力修复他们。
如果后续有什么其他bug，欢迎指出。

关于第3点，希望可以附带上出错的视频链接，非常感谢！！

**Comment by racedeyu** [comment]
最后一点个问题其实不太好复现，一般出现在国内没有版权的番上，例如这个 [https://www.agefans.net/play/20200036?playid=3_11](url)

**Comment by IronKinoko** [comment]
我这边是点开就能播放了, 没有重现你反馈的问题.
想了下可能的原因
- 最有可能的是页面是部署在`github pages`上的 这个加载不出来的可能性最高
- 外部cdn加载失败了 用的是 [jsdelivr](https://www.jsdelivr.com/) 这个有时候会挂掉 但是大部分是正常的
- agefans的视频地址 用的是各大公司的cdn存储 可能有时候加载慢了 看起来像是没出来

**Comment by racedeyu** [comment]
应该不是github page的问题因为这个域名我是走代理的。另外，不用用户脚本agefans也有这个问题，会直到浏览器连接超时都加载不上，刷新一下又好了，也有可能是我的网络（深圳电信）问题，不过热门资源倒是没有问题。
