### ISSUE TITLE
大佬好，有个问题想请教

### ISSUE THREAD

**Issue by LChener** [IronKinoko/agefans-enhance#32]
### 简要描述下需要的功能、意见或建议

有些视频会显示“这个视频似乎是第三方链接，并非由agefans自身提供，将使用默认播放器播放”，请问需要如何设置才能让脚本正常在这种视频页面运行呢？

**Comment by IronKinoko** [comment]
这个不打算支持的，太麻烦了。他是外链，而且还特别慢
我建议是去其他的站点看

**Comment by LChener** [comment]
明白了，感谢作者开发，现有功能也完全能够满足需求！
