### ISSUE TITLE
快捷键

### ISSUE THREAD

**Issue by akikans** [IronKinoko/agefans-enhance#36]
### 简要描述下需要的功能、意见或建议

快进/快退60s的快捷键（alt+←/→)与edge浏览器的前进/后退相同，可否做一下调整

**Comment by IronKinoko** [comment]
是因为占用后导致网页前进/后退不能用了吗？

这个键位已经有段时间了。应该不打算改

**Comment by akikans** [comment]
是这样。
那就如此吧
