### ISSUE TITLE
下载链接的m3u8文件用mpv不能播放

### ISSUE THREAD

**Issue by happytommyl** [IronKinoko/agefans-enhance#37]
### 简要描述下需要的功能、意见或建议

下载链接的m3u8文件用mpv和vlc都不能播放，打开看内容只有.jpg的链接，但是用idm可以直接转换成ts文件。请问是mpv的问题吗？

**Comment by IronKinoko** [comment]
应该是网络请求header不对吧，资源站点服务端安全校验防止盗链。
我没有这两个播放器，无法具体帮到你。以上只是猜测。
