### ISSUE TITLE
播放器功能建议

### ISSUE THREAD

**Issue by zly49** [IronKinoko/agefans-enhance#39]
### 简要描述下需要的功能、意见或建议

希望添加快进按钮或者更方便的是支持触屏操作(例如双击快进)
不知道这技术上能不能实现
感谢开发者!

**Comment by IronKinoko** [comment]
触屏啊。。。目前的 UI 在触屏设备上应该挺难用的。项目主要写给 pc 的，所以暂时不考虑吧

先试着用进度条拖动吧

**Comment by zly49** [comment]
> 触屏啊。。。目前的 UI 在触屏设备上应该挺难用的。项目主要写给 pc 的，所以暂时不考虑吧
> 
> 先试着用进度条拖动吧

在播放键旁添加快进和快退按钮来实现小幅度的控制是否可以作为一个过度方案
