### ISSUE TITLE
🐛[Bug]樱花动漫无法播放

### ISSUE THREAD

**Issue by momoblydblk** [IronKinoko/agefans-enhance#40]
# 文字描述
樱花动漫无法播放，但是在禁用脚本之后可以播放。
樱花移动版网页都可以播放。

# 网址链接
https://www.yhdmp.cc/vp/22172-1-10.html

# 视频链接
（同上）

# 环境
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0
脚本版本: 1.25.3

**Comment by IronKinoko** [comment]
你发的这个链接，我这边脚本是打开看的。会是当时的网络问题吗？

**Comment by momoblydblk** [comment]
> 你发的这个链接，我这边脚本是可以打开看的。会是当时的网络问题吗？

脚本不改变解析目标吧？不改变的话就很奇怪，脚本禁用可以播，但一开就卡加载。如果改了的话说不定是解析源的问题

**Comment by momoblydblk** [comment]
我等会确认下和其他拓展有没有关系

**Comment by momoblydblk** [comment]
控制台有两个和agefans-enhance有关的报错
![图片](https://user-images.githubusercontent.com/21081757/174213789-b1938cd1-deb7-4e46-81d3-a13633ee19f1.png)

和
![图片](https://user-images.githubusercontent.com/21081757/174213766-7b49baef-cd6f-409c-8527-c6f111d9656a.png)

**Comment by IronKinoko** [comment]
看来是资源没有下载到导致报错了，使用了 unpkg 的 CDN。

**Comment by IronKinoko** [comment]
这下真不知道了，我使用与你相同的浏览器(firefox 101.0.1)还是能够播放
