### ISSUE TITLE
弹幕匹配问题

### ISSUE THREAD

**Issue by LChener** [IronKinoko/agefans-enhance#41]
### Bug 网页链接

https://www.agemys.cc/play/20220142?playid=2_1

**Comment by IronKinoko** [comment]
目前看弹幕是正常的，你可以检查下弹幕是否选错章节了

**Comment by LChener** [comment]
已解决，感谢。（不过昨天可以确定没有选错）

**Comment by IronKinoko** [comment]
好的，我后续再留意下吧，自己还没有遇到过

**Comment by kaedei** [comment]
> 已解决，感谢。（不过昨天可以确定没有选错）

因为是看到反馈后手工修复的，所以以后发现问题可以到弹弹反馈区去报告关联错误。当然也可以等数据自行修复，但那需要些时间。
