### ISSUE TITLE
跟进部分新功能

### ISSUE THREAD

**Issue by IronKinoko** [IronKinoko/agefans-enhance#42]
来源：https://greasyfork.org/zh-CN/scripts/424023-agefans-enhance/discussions/141196

- [x] 支持导入 bilibili 弹幕屏蔽设置 xml 导入
- [x] 上一帧/下一帧功能与快捷键
- [x] 快捷键自定义
- [x] 弹幕屏蔽支持正则表达式
- [x] 支持导入 bilibili 弹幕屏蔽设置 json 导入
- [ ] 修改弹幕设置框显示隐藏逻辑
- [x] 支持所有按键自定义

**Comment by MC-dusk** [comment]
您好，我就是greasy发问题的，star了支持一下。

想兼容用[h5player](https://github.com/xxxily/h5player)主要是逐帧很香，就是按d/f键上一帧/下一帧，其他的增强功能用的不多。不过不能兼容就算了，目前已经很好了。

**Comment by MC-dusk** [comment]
关于`导入 bilibili 弹幕屏蔽`（最近更新的1.27.5版本）的反馈：

B站部分用户灰度更新到3.x版本播放器，此时只能导出json屏蔽列表，但可以导入json或xml；2.x播放器只支持导入导出xml格式屏蔽列表。

如果有不能导出xml屏蔽列表的可以暂时用下这个网站的[屏蔽词包](https://harrynull.tech/bilibili/)

**Comment by IronKinoko** [comment]
@MC-dusk 我不在灰度范围内，看不到json格式，你可以发我一份文件吗？

**Comment by MC-dusk** [comment]
```
[{"type":2,"filter":"35f7e9c4","opened":true,"id":0},{"type":2,"filter":"51dff025","opened":true,"id":0},{"type":2,"filter":"146028de","opened":true,"id":0},{"type":0,"filter":"还愿","opened":true,"id":0},{"type":0,"filter":"祝我","opened":true,"id":0},{"type":0,"filter":"许愿","opened":true,"id":0},{"type":0,"filter":"录取","opened":true,"id":0},{"type":0,"filter":"祈愿","opened":true,"id":0},{"type":0,"filter":"保抽","opened":true,"id":0},{"type":0,"filter":"佑我","opened":true,"id":0},{"type":2,"filter":"2e2ce2bd","opened":true,"id":0},{"type":2,"filter":"d85e6630","opened":true,"id":0},{"type":2,"filter":"b21afeb5","opened":true,"id":0},{"type":2,"filter":"9bb07709","opened":true,"id":0},{"type":2,"filter":"6f143ebb","opened":true,"id":0},{"type":1,"filter":"小 *鬼","opened":true,"id":0},{"type":1,"filter":"有毛?病","opened":true,"id":0},{"type":1,"filter":"^寂寞₍.*₎$","opened":true,"id":0}]
```

**Comment by 0936ztx** [comment]
有些番全网都搜不到弹幕的话考不考虑开一个发弹幕的功能呢？

**Comment by IronKinoko** [comment]
@0936ztx 脚本使用人数有限，增加不了多少弹幕的

**Comment by MC-dusk** [comment]
> 有些番全网都搜不到弹幕的话考不考虑开一个发弹幕的功能呢？

可以去[弹幕盒子](https://danmubox.github.io/search)搜搜看，不过脚本没有加载本地弹幕的功能，把视频下下来用弹弹play或bililocal播放弹幕吧
