### ISSUE TITLE
添加对N站弹幕的支持

### ISSUE THREAD

**Issue by DeltaFlyerW** [IronKinoko/agefans-enhance#43]
添加对N站弹幕的支持

https://delflare505.win:800
备用地址 http://152.32.146.234:400

api:

/nico/?xml=1&nicoid=so40732397&translate=1&translateThreshold=7&niconum=3000

[ ] 接受参数

1. nicoid:n站视频ID
2. translate:设为1则启用机翻
3. translateThreshold:长度小于N的的弹幕将不被翻译
4. niconum:返回的最大弹幕数量

[ ] 响应内容:
哔哩哔哩风格的xml弹幕

/searchNicoChannel?keyword=異世界

[ ] 接受参数

1. keyword:关键字,用空格分割开则匹配任意字符

[ ] 响应内容:
目前服务器已缓存的含关键字的动画列表
[{"channel": 2646899, "title": "無職転生 異世界行ったら本気だす", "so_list": ".37909436.37981417.38080161.38113546.38142793.38181671.38216598.38251296.38287497.38324157.38359917.38397733.38449918.39380696.39410591.39443233.39476786.39511362.39543461.39577451.39607487.39638041.39668968.39700040.39729881.39761890."}]

[TODO]
添加一个api,以将弹弹匹配的视频信息与N站番剧绑定
添加一个api,接受弹弹信息和集数,返回对应的弹幕
具体api内容需要进一步讨论

**Comment by IronKinoko** [comment]
非常感谢你提供这么详细的说明

番剧弹幕接口是弹弹play提供的，恐怕没有无法拓展nico，需要向他们提交需求
