### ISSUE TITLE
🐛[Bug] bangumi.online 上失效

### ISSUE THREAD

**Issue by asadahimeka** [IronKinoko/agefans-enhance#47]
# 文字描述

脚本在 bangumi.online 上失效，播放器好像没有被完全替换，没有弹幕按钮
控制台报错：
![image](https://user-images.githubusercontent.com/31837214/179404433-f8729c97-a9b7-474e-bf3a-ca5619c3dbe3.png)

# 网址链接
https://bangumi.online/watch/PBK8O82x7MCMPQbW

# 视频链接
blob:https://bangumi.online/d9dd27ef-fc3e-4401-8ec7-020bd28e444b

# 环境
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62
脚本版本: 1.27.4

**Comment by IronKinoko** [comment]
已修复。
很久没用这个网站，它网页可能改版了，所以报错了
