### ISSUE TITLE
元素遮挡

### ISSUE THREAD

**Issue by rcyggdra** [IronKinoko/agefans-enhance#5]
https://www.agefans.net/play/20210066?playid=2_5
这提示遮挡了视频，网页应该是正常播放视频的，有声音。
![image](https://user-images.githubusercontent.com/8652464/117565226-b32b7800-b0e2-11eb-831b-e919ae909543.png)

**Comment by IronKinoko** [comment]
更新到最新的脚本（1.1.2 版本），解决这个提示框
