### ISSUE TITLE
匹配不到番剧

### ISSUE THREAD

**Issue by Qinks6** [IronKinoko/agefans-enhance#50]
### Bug 网页链接

http://www.yinghuacd.com/v/5531-5.html

### 简要描述下问题

插件版本:1.28.0
Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
    at ABPlayer.min.js:2:9649

**Comment by IronKinoko** [comment]
弹弹player的弹幕服务挂了，过段时间再试试吧。我这边持续跟进下

**Comment by IronKinoko** [comment]
弹弹player 作者微博 [@Kaedei](https://weibo.com/u/1489307232)

![image](https://user-images.githubusercontent.com/32838658/185823805-1026ed71-9819-494e-8431-371d91b46129.png)

**Comment by IronKinoko** [comment]
弹幕已修复 [v1.28.3](https://greasyfork.org/scripts/424023)
