### ISSUE TITLE
弹幕

### ISSUE THREAD

**Issue by bingcha12138** [IronKinoko/agefans-enhance#52]
### 简要描述下需要的功能、意见或建议

看热门番剧高能片段的时候，弹幕密度过大而且有重叠现象，能否出一个合并重复弹幕功能或者优化弹幕密度？谢谢大佬。

**Comment by IronKinoko** [comment]
弹幕过多导致重叠是难免的。设置里有个弹幕密度设置，以 3000条/24分钟 为基准自由调整。

弹幕合并可以考虑，我后续再看看
