### ISSUE TITLE
希望适配这个樱花www.odcoc.com/play/再加点小建议

### ISSUE THREAD

**Issue by tianweichangge** [IronKinoko/agefans-enhance#54]
### 简要描述下需要的功能、意见或建议

希望适配这个樱花 www.odcoc.com ，最近动漫网站好像总有资源缺失看不了，只好几个网站轮流用。所以很需要弹幕啊。另外提点小建议，
1）所有适配的网站要不来个汇总，方便而且共享资源
2）以及快进都是5秒的，能不能有3倍速播放呢。再加一个快捷键直接快进一分25秒更合适吧，因为op大多是一分半这个时间。
3）还有按n下一集它又会退出全屏，能不能改进一下。（当然再等几秒刷新好按f全屏也行，但可以的话希望改进)
总之于我而言，弹幕还有快捷键下一集和全屏，这三个功能就满足需求了

**Comment by IronKinoko** [comment]
适配的网站可以使用【友链】访问

快进时间可以查看快捷键，搭配 ctrl shift alt 可以 5s 30s 90s 跳转

部分网站切换下一集会刷新页面退出全屏，浏览器不允许代码主动全屏页面，所以做不到

所有快捷键使用【？】键查看，都可以自定义

**Comment by tianweichangge** [comment]
这样啊，明白了。试了试自定义快捷键，真是太棒了。不过还有想说的，1）跳转可以有一个85s的更实用，90s总会跳多几秒。2）倍速播放可不可以增加个像b站一样，就是长按快捷键倍速播放，松开恢复原速。另外没想到有个惊喜的功能之前没注意，居然有上一帧下一帧，按一下到指定画面还是暂停状态，啊啊斯巴拉西
