### ISSUE TITLE
大佬能添加这个网站吗https://www.nivod.tv/index.html

### ISSUE THREAD

**Issue by RRRRRqing** [IronKinoko/agefans-enhance#55]
### 简要描述下需要的功能、意见或建议

这绝对是我见过更新速度最快且高清无广告的在线视频网站了 要梯子）片源质量都很棒就是没弹幕很可惜so sad

**Comment by RRRRRqing** [comment]
或者说可以自主添加视频网站吗（
还有就是有个疑惑不知道怎么解决 像阿b这种网站这几年新番删减比较严重 视频时间很多不是完整的24分钟 有的直接只有22分钟 这样的话弹幕轴不就会错位吗？

**Comment by IronKinoko** [comment]
如果你会写 ts，欢迎提交 pr，参考 adapter 文件夹里的
一般是不好适配的，网站一般都存在混淆/加密之类的操作，需要研究下

弹幕是 dandanplay 提供的，根据我使用的经验是会存在错位的问题。但太不常见，也有快捷键可以调整弹幕时间轴

**Comment by RRRRRqing** [comment]
> 如果你会写 ts，欢迎提交 pr，参考 adapter 文件夹里的 一般是不好适配的，网站一般都存在混淆/加密之类的操作，需要研究下
> 
> 弹幕是 dandanplay 提供的，根据我使用的经验是会存在错位的问题。但太不常见，也有快捷键可以调整弹幕时间轴

明白了 但是我不会呜呜呜
