### ISSUE TITLE
获取的B站弹幕集数不对

### ISSUE THREAD

**Issue by zxzlf** [IronKinoko/agefans-enhance#58]
### Bug 网页链接

https://www.yhdmp.cc/vp/22203-1-3.html

### 简要描述下问题

今天看孤独摇滚第四集，结果好像把B站第一集的弹幕也弄进来了
弹幕能否根据来源选择性开启？

**Comment by IronKinoko** [comment]
弹幕数据问题是 弹弹play 的bug，我只能反馈下

什么是【弹幕能否根据来源选择性开启】？弹幕来源是多个站点合并的，是想自主选择来源吗？
如果是我理解的这样，我可以加加看

**Comment by zxzlf** [comment]
> 弹幕数据问题是 弹弹play 的bug，我只能反馈下
> 
> 什么是【弹幕能否根据来源选择性开启】？弹幕来源是多个站点合并的，是想自主选择来源吗？ 如果是我理解的这样，我可以加加看
我的确是这个意思，主要是有时候巴哈之类的弹幕用词和大陆的区别过大，理解起来比较费劲，还得脑内转换一遍，就想看能不能只获取简体弹幕
之前在折腾电脑，才看到回复，不好意思哈

**Comment by IronKinoko** [comment]
我近期研究下

**Comment by IronKinoko** [comment]
可以更新了 [v1.35.0](https://greasyfork.org/scripts/424023)

**Comment by zxzlf** [comment]
> 可以更新了 [v1.35.0](https://greasyfork.org/scripts/424023)

试了一下，效果相当好👍
