### ISSUE TITLE
部分合作网页的视频加载失败？

### ISSUE THREAD

**Issue by lirener** [IronKinoko/agefans-enhance#59]
### Bug 网页链接

https://www.yhdmp.cc/vp/22304-1-4.html

### 简要描述下问题

脚本版本号：1.33.0
游览器版本号：Chrome版本 106.0.5249.119（正式版本） （64 位）
问题网页：（樱花动漫）www.yhdmp.cc
问题描述：视频转圈圈加载失败，关闭脚本用自带播放器正常
该问题出现时间：大概好久了……具体也忘了几个星期可能有……看没什么人提
![QQ截图20221117004338](https://user-images.githubusercontent.com/19354130/202241791-04465382-b53e-4704-bdf1-5064008072a3.png)

**Comment by lirener** [comment]
和这个同学的问题差不多：https://github.com/IronKinoko/agefans-enhance/issues/40

**Comment by lirener** [comment]
通过抓包 解析到的M3U8网页播放正常（谷歌M3U8播放器插件）：
https://yun.ssdm.cc/SBDM/FutokunoGuild06.m3u8



</body>
</html>

**Comment by lirener** [comment]
随便抓了一句控制台提示错误：
`Access to XMLHttpRequest at 'https://ke-image.ljcdn.com/rent-front-image/5b530372cd63cf49fab0ff6511c2c1b4.png' from origin 'https://www.yhdmp.cc' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
userscript.html?name=agefans%2520Enhance.user.js&id=b9693d98-3392-478f-bfdb-7faa7f672edd:10          GET https://ke-image.ljcdn.com/rent-front-image/5b530372cd63cf49fab0ff6511c2c1b4.png net::ERR_FAILED 403`
有这些 够修复了不？
![QQ截图20221117010628](https://user-images.githubusercontent.com/19354130/202246619-d9a718f5-63d9-474b-aab6-ad11c05fe888.png)
![QQ截图20221117010636](https://user-images.githubusercontent.com/19354130/202246640-de629346-dd8f-4009-90c6-1d234f5e020a.png)

**Comment by IronKinoko** [comment]
这个是资源有问题，修复不了的。就算关闭了脚本也播放不了

**Comment by IronKinoko** [comment]
可以更新了 [v1.34.1](https://greasyfork.org/zh-CN/scripts/424023-agefans-enhance)

**Comment by lirener** [comment]
> 可以更新了 [v1.34.1](https://greasyfork.org/zh-CN/scripts/424023-agefans-enhance)

good job！~
![X_T~%A3@1K UVH{KI41 0(Q](https://user-images.githubusercontent.com/19354130/202379630-76a882fa-aad9-4e16-b835-06a069357565.gif)
