### ISSUE TITLE
历史记录移除

### ISSUE THREAD

**Issue by rcyggdra** [IronKinoko/agefans-enhance#60]
### 简要描述下需要的功能、意见或建议

在历史记录，希望能有移除功能，例如缩略图右上角弄个“X”；又或者有个能进入编辑功能的。

也希望能有个“是否开启历史记录”的功能。

**Comment by IronKinoko** [comment]
记录的数据都是本地，真的需要这种编辑需求吗？

**Comment by rcyggdra** [comment]
> 记录的数据都是本地，真的需要这种编辑需求吗？

记得以前是cookies的，随时可以清，现在存在脚本里，清理变得繁琐。
我是那种退出浏览器就清理历史记录的，除了某些常去的网站，我都不设置保存cookies，
也还没到用沙箱那种地步，就是不想有历史记录留下。
现在脚本最大的问题是，某些番剧就是随便点进去看下，它又记录了，我也不会继续看，但它却是一直存在列表里……
强迫症犯了。
