### ISSUE TITLE
部分友链域名更新后播放器功能失效

### ISSUE THREAD

**Issue by lirener** [IronKinoko/agefans-enhance#61]
### 简要描述下需要的功能、意见或建议

NT动漫：http://www.ntyou.cc/ 更新域名为 http://www.ntdm8.com/ 后
大部分功能失效……比如热键：【W】网页全屏失效……、鼠标移动到友链按钮也不弹出内容……
已经试着从脚本里添加域名……但是不起作用
![QQ截图20230119002402](https://user-images.githubusercontent.com/19354130/213235489-d8cd7f24-8d82-414a-a804-6b64e59142cc.jpg)
![舰娘poi咬手手啊呜](https://user-images.githubusercontent.com/19354130/213235385-344579a1-f898-4c20-bcda-c6fbd59526ac.jpg)

**Comment by IronKinoko** [comment]
感谢反馈！已经修改发布 [v1.36.6](https://greasyfork.org/zh-CN/scripts/424023-agefans-enhance)

**Comment by lirener** [comment]
![阿尼亚抬头哇兴奋开心](https://user-images.githubusercontent.com/19354130/213247962-23446022-f415-46b2-a352-00d234fe8bfb.gif)
动作真快！开心~问题已解决！

**Comment by IronKinoko** [comment]
重新发布了 [1.36.7](https://greasyfork.org/zh-CN/scripts/424023-agefans-enhance) 版本，修复友链打不开的问题，并且调整了下播放器的窗口高度，让播放器两边的黑边消失。
