### ISSUE TITLE
🐛[Bug]提示弹幕服务异常，请稍后再试

### ISSUE THREAD

**Issue by zpoyqx** [IronKinoko/agefans-enhance#64]
# 文字描述
提示弹幕服务异常，请稍后再试

# 网址链接
http://www.ntdm8.com/play/4834-1-6.html

# 视频链接
http://v16m-default.akamaized.net/48a4831f8ee850bd39fa74f558639fa5/646772e2/video/tos/alisg/tos-alisg-v-0000/okSEgQZIpSo7BQkeqeOvDuDvknP2b3AoNUB1lQ/?a=2011&ch=0&cr=0&dr=0&net=5&cd=0%7C0%7C0%7C0&br=3316&bt=1658&cs=0&ds=4&ft=iJOG.y7oZZv0PD13RmIXg9wz.DKlBEeC~&mime_type=video_mp4&qs=0&rc=OzY0NmU7NzpnOTc3OWc1O0BpM243Zzo6ZnVoazMzODYzNEAxMTMuMTU2XjUxMmEzNWBeYSNjZjZucjRvbmZgLS1kMC1zcw%3D%3D&l=202305190635179937CB8D451C897A3DC8&btag=e00080000

# 环境
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42
脚本版本: 1.36.11

**Comment by IronKinoko** [comment]
我这里访问正常的，你稍后再试试看吧
