### ISSUE TITLE
功能请求：记住播放列表的排序状态

### ISSUE THREAD

**Issue by XHXIAIEIN** [IronKinoko/agefans-enhance#68]
### 简要描述下需要的功能、意见或建议

> 播放平台：AGE动漫
> 示例地址：https://www.agemys.org/play/20000001/3/918

请求1：记住页面 “更改排序” 的状态。
目前页面发生跳转的时候（包括播放下一集），页面会重置 “更改排序” 的状态。像海贼王这种上千集的动漫，播放列表会非常长，每次都要手动切换一次，非常麻烦。
![Snipaste_2023-08-01_21-04-32](https://github.com/IronKinoko/agefans-enhance/assets/45864744/7c926c6c-7d41-4137-9714-8cdd5fb82bea)
  
  
请求2：集数列表的滚动条可以自动跳转至当前集数的位置。如果继续添加一个定位按钮，允许手动快速跳转就更好了。
![Snipaste_2023-08-01_21-08-21](https://github.com/IronKinoko/agefans-enhance/assets/45864744/c51bf8c2-d78a-4c90-b6f8-cffc7f0f11de)

**Comment by IronKinoko** [comment]
做完了， 更新吧 [v1.38.0](https://greasyfork.org/scripts/424023)

**Comment by XHXIAIEIN** [comment]
太强了！

**Comment by XHXIAIEIN** [comment]
对了，聚焦的按钮，要是能跳转回播放源的标签页就更方便了~ 网址的第二个参数就是播放源

**Comment by IronKinoko** [comment]
改好了 [v1.38.2](https://greasyfork.org/scripts/424023)
