### ISSUE TITLE
功能请求：在全屏状态播放下一集，可以自动回到全屏

### ISSUE THREAD

**Issue by XHXIAIEIN** [IronKinoko/agefans-enhance#69]
### 简要描述下需要的功能、意见或建议

> 播放平台：AGE动漫
> 示例地址：https://www.agemys.org/play/20000001/3/920

在全屏播放的状态，点击下一集或自动播放下一集，页面跳转后，可以自动回到全屏状态。（包括：网页全屏或全屏）
![image](https://github.com/IronKinoko/agefans-enhance/assets/45864744/8597fda7-60e2-44c5-a487-882582779536)

**Comment by IronKinoko** [comment]
## 网页全屏
自动网页全屏目前已经做到了

## 全屏
浏览器安全问题，禁止切换页面后自动全屏，必须有用户交互后才能全屏

解决方案：
改成接口获取视频链接，在原网页上的动态替换视频源。是能改，但不好改，先这样用着吧

这个需求先挂着

**Comment by suxing-soon** [comment]
鉴于网址经常改变，插件也随之失效，请问下dalao能不能设置一个接口，可以随时替换视频源？
实现：即使网址改变了，只需自己添加新的视频链接，就可搭配弹幕观看。
请问下大佬这样能不能实现呢，谢谢您。

**Comment by suxing-soon** [comment]
> ## 网页全屏
> 自动网页全屏目前已经做到了
> 
> ## 全屏
> 浏览器安全问题，禁止切换页面后自动全屏，必须有用户交互后才能全屏
> 
> 解决方案： 改成接口获取视频链接，在原网页上的动态替换视频源。是能改，但不好改，先这样用着吧
> 
> 这个需求先挂着

鉴于网址经常改变，插件也随之失效，请问下dalao能不能设置一个接口，可以随时替换视频源？
实现：即使网址改变了，只需自己添加新的视频链接，就可搭配弹幕观看。
请问下大佬这样能不能实现呢，谢谢您。

**Comment by IronKinoko** [comment]
> 鉴于网址经常改变，插件也随之失效，请问下dalao能不能设置一个接口，可以随时替换视频源？
> 实现：即使网址改变了，只需自己添加新的视频链接，就可搭配弹幕观看。
> 请问下大佬这样能不能实现呢，谢谢您。

@suxing-soon 我研究下吧。

让用户适配站点有点难，需要一定的编码能力。视频链接经常是加密传输，得调试过后才知道解密逻辑。

**Comment by XHXIAIEIN** [comment]
agemys.org
播放器好像又失效了，没有播放下一集的按钮

**Comment by IronKinoko** [comment]
更新 [v1.38.4](https://greasyfork.org/scripts/424023) 适配 agefans 了

**Comment by IronKinoko** [comment]
更新 [v1.39.2](https://greasyfork.org/scripts/424023) 优化了 agefans 的播放体验
做了无缝换集、保留全屏、自动播放等功能
