### ISSUE TITLE
请添加使用说明

### ISSUE THREAD

**Issue by petterbj** [IronKinoko/agefans-enhance#7]
您好，请问这个项目有没有安装说明或者使用说明呀？

https://ironkinoko.github.io/agefans-enhance/

这个网址打开后一直在转圈😂
不知道怎么使用

**Comment by IronKinoko** [comment]
😂你难道是直接在github里搜出来的吗？一般他们是从油猴过来的，所以就没写使用说明了，我有空补一下

安装下脚本就行
# 安装
https://greasyfork.org/zh-CN/scripts/424023-agefans-enhance

**Comment by petterbj** [comment]
😅确实是在github里搜出来的，

谢谢！
