### ISSUE TITLE
BUG反馈：自动播放不起作用

### ISSUE THREAD

**Issue by XHXIAIEIN** [IronKinoko/agefans-enhance#70]
### Bug 网页链接

https://www.agemys.org/play/20000001/3/920

### 简要描述下问题

我已经勾选了 "自动播放"，但不管是点击下一集还是自动下一集，新页面依然是黑屏等待播放状态。

![image](https://github.com/IronKinoko/agefans-enhance/assets/45864744/d25d3202-6640-4c61-a833-3270027b2082)

![image](https://github.com/IronKinoko/agefans-enhance/assets/45864744/db5d4dec-e44b-4294-b636-94a5a32a4ef9)

**Comment by IronKinoko** [comment]
原因：
由于浏览器安全策略问题，不支持带声音的视频自动播放

解决方案：
再多看看，看久了以后，浏览器就会记住你经常使用这个网址，之后会允许自动播放。
