### ISSUE TITLE
🐛acgnya问题

### ISSUE THREAD

**Issue by MrPinku** [IronKinoko/agefans-enhance#71]
# 文字描述

![image](https://github.com/IronKinoko/agefans-enhance/assets/79267206/1b49c5c1-e542-4dfe-93b4-8ecafeade00f)
连播下一集会给这个界面挡住需要手动点才能播放，希望可以解决

# 网址链接
https://www.acgnya.com/vodplay/1916-1-22/

# 视频链接
https://s138.ananas.chaoxing.com/sv-w8/video/12/e8/4a/5b916d563e8d54df9193a8497dd220a9/sd.mp4

# 环境
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
脚本版本: 1.38.2

**Comment by IronKinoko** [comment]
更新 [1.38.3](https://greasyfork.org/zh-CN/scripts/424023-agefans-enhance)
