### ISSUE TITLE
进入全屏后经常会立刻自动退出全屏并刷新页面

### ISSUE THREAD

**Issue by bf179** [IronKinoko/agefans-enhance#73]
### Bug 网页链接

https://www.ntdm9.com/play/5074-1-1.html 和 https://www.agemys.org/play/20220513/1/1

### 简要描述下问题

点击全屏后会立刻自动退出并刷新页面，偶尔复现，播放器加载完成后多等一会儿会有改善，但是仍会有该问题。
关闭本脚本则正常全屏。

**Comment by IronKinoko** [comment]
我这里复现不了，试着换一个浏览器看看？

这个问题我先挂着吧，看后续有没有其他人也出现这种情况
