### ISSUE TITLE
nt动漫个别番剧出现弹幕时间错位情况

### ISSUE THREAD

**Issue by thouser8** [IronKinoko/agefans-enhance#76]
### Bug 网页链接

http://www.ntdm9.com/play/1678-1-6.html

### 浏览器信息

Microsoft Edge 版本 118.0.2088.57 (正式版本) (64 位) ,Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.57

### 简要描述下问题

看哥布林杀手会出现1.每一集的弹幕都需要自行选择正确的单集进行配对。
2.弹幕时间略慢于实际画面，大概延迟了四五秒。

**Comment by IronKinoko** [comment]
弹幕服务由第三方(弹弹play)提供，弹幕数据是收录自不同平台，可能不是观看同一个视频源，只能手动调整下时间

**Comment by thouser8** [comment]
> 弹幕服务由第三方(弹弹play)提供，弹幕数据是收录自不同平台，可能不是观看同一个视频源，只能手动调整下时间

没找到哪里可以手动调整弹幕时间，烦请告诉我一下

**Comment by IronKinoko** [comment]
![image](https://github.com/IronKinoko/agefans-enhance/assets/32838658/a1f56d67-3d77-4b62-88e0-064ef0c3e24a)
弹幕调整相关的快捷键
