### ISSUE TITLE
导入不了xml格式的弹幕

### ISSUE THREAD

**Issue by yishengrenshijian** [IronKinoko/agefans-enhance#77]
### Bug 网页链接

https://www.ntdm9.com/play/3560-2-12.html

### 简要描述下问题

image
怎么导入不了xml格式的弹幕呀

**Comment by yishengrenshijian** [comment]
求助作者

**Comment by IronKinoko** [comment]
这里是导入【弹幕屏蔽列表】，不是导入弹幕。
弹幕目前没办法导入。请使用内置的搜索服务看弹幕。

**Comment by yishengrenshijian** [comment]
谢谢解答
