### ISSUE TITLE
脚本失效了

### ISSUE THREAD

**Issue by Cat0x1** [IronKinoko/agefans-enhance#78]
### Bug 网页链接

https://m.agedm.org/#/play/20220268/1/1

### 浏览器信息

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

### 简要描述下问题

![image](https://github.com/IronKinoko/agefans-enhance/assets/58590403/83e9cdf0-450a-4bd3-ae5f-cb1f83a84281)
脚本失效，重复安装过多次。
![image](https://github.com/IronKinoko/agefans-enhance/assets/58590403/85049490-9e20-44a9-9936-f4286f6532c7)

**Comment by IronKinoko** [comment]
适配了，更新下版本 [v1.41.1](https://greasyfork.org/zh-CN/scripts/424023-agefans-enhance)
