### ISSUE TITLE
ipad safari 安装脚本不起作用

### ISSUE THREAD

**Issue by hyrulelinks** [IronKinoko/agefans-enhance#79]
如题，ipad safari浏览器安装脚本后依然使用safari或网站自己默认的播放器，没有替换成功，但在mac safari上安装脚本是正常起作用的，可否修复或提供ipad支持，谢谢！

**Comment by IronKinoko** [comment]
需要发下你观看的链接，或者描述下是哪个网站

**Comment by hyrulelinks** [comment]
是支持网站列表里的所有网站挨个试了都不起作用

**Comment by IronKinoko** [comment]
经过别的用户反馈，应该是某项资源链接失效了，导致脚本在新的设备上无法使用。但是老设备使用的是缓存所以不会有影响。

你如果还在用的话，可以安装1.43.2版本
