### ISSUE TITLE
可否在弹幕设置里增加一个下载弹幕文件的功能

### ISSUE THREAD

**Issue by hyrulelinks** [IronKinoko/agefans-enhance#80]
### 简要描述下需要的功能、意见或建议

有些好片想用高清版本在本地再看一边，如果有弹幕下载功能就好了，谢谢作者

**Comment by IronKinoko** [comment]
你可以搜索弹弹play播放器，应该会帮到你

**Comment by hyrulelinks** [comment]
> 你可以搜索弹弹play播放器，应该会帮到你

嗯，windows上还行，不过我日常主力机用的是macbook pro，mac版弹弹player已经几年没更新了，老版使用体验非常难绷，或者作者是否可以为阿里云盘的播放器写个脚本增加弹幕功能，这样用阿里云看高清的时候也能有弹幕，比本地要更方便些

**Comment by IronKinoko** [comment]
那挺遗憾的，我这边应该不会加这个功能

关于你有更清晰的视频源文件，你可以打开相同番剧的在视频播放网站（其实任意番剧都行，主要是方便搜索匹配到弹幕），将你本地的源文件拖入到在线播放器中，它会将视频替换成你拖入的高清视频

**Comment by hyrulelinks** [comment]
> 那挺遗憾的，我这边应该不会加这个功能
> 
> 关于你有更清晰的视频源文件，你可以打开相同番剧的在线视频播放网站（其实任意番剧都行，主要是方便搜索匹配到弹幕），将你本地的源文件拖入到在线播放器中，它会将视频替换成你拖入的高清视频

还有这种操作啊，完全不知道，我等下试试

**Comment by hyrulelinks** [comment]
> 那挺遗憾的，我这边应该不会加这个功能
> 
> 关于你有更清晰的视频源文件，你可以打开相同番剧的在线视频播放网站（其实任意番剧都行，主要是方便搜索匹配到弹幕），将你本地的源文件拖入到在线播放器中，它会将视频替换成你拖入的高清视频

试了下还真可以，打开新世界大门了，就是高清都存在云盘上，需要重新下载来看，多少有些不便，如果云盘播放器直接可以弹幕就好了
