### ISSUE TITLE
脚本失效

### ISSUE THREAD

**Issue by OedoSoldier** [IronKinoko/agefans-enhance#82]
### Bug 网页链接

https://www.agedm.org/play/20240118/1/2

### 浏览器信息

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

### 简要描述下问题

前几天还好用，现在所有网站都不起作用，脚本似乎都没有加载，怀疑是 Chrome 版本问题。

**Comment by IronKinoko** [comment]
Chrome 版本 126.0.6478.183（正式版本） (x86_64)
我的版本是这个，目前可用。
你发下篡改猴的版本看看

**Comment by OedoSoldier** [comment]
> Chrome 版本 126.0.6478.183（正式版本） (x86_64) 我的版本是这个，目前可用。 你发下篡改猴的版本看看

我之前是 5.1.1，刚刚升级到 5.2.3 但还是不行。

用我笔记本电脑试了下，笔记本电脑是 1.41.1 版本的脚本（篡改猴 5.1.1，Chrome 126.0.0.0），测试可行；然后我升级到 1.43.1 版本的脚本之后就不行了，再降级回 1.41.1 版本依然不可用。似乎和 Chrome 版本无关。

**Comment by IronKinoko** [comment]
篡改猴插件 -> 设置 -> 安全 -> Userscript @include Mode
改成unsafe试试看？

**Comment by OedoSoldier** [comment]
经检查是无法连接 `registry.npmmirror.com` 导致的。

![https://i.imgur.com/57g6WoU.png]

**Comment by IronKinoko** [comment]
这个镜像被灰产恶意白嫖了流量，开启了白名单模式，自由注册的资源和热门资源提供访问

**Comment by IronKinoko** [comment]
脚本更新了，1.43.2 将资源换成 unpkg.com 了
