### ISSUE TITLE
更新请求:  ''次元城动画''网址变更

### ISSUE THREAD

**Issue by SankaRea233** [IronKinoko/agefans-enhance#85]
### 简要描述下需要的功能、意见或建议

大佬帮帮忙,自己尝试修改代码无果qwq

新网址www.cyc-anime.net

**Comment by IronKinoko** [comment]
更新 [v1.43.4](https://greasyfork.org/zh-CN/scripts/424023) 版本

**Comment by SankaRea233** [comment]
谢谢大佬


っ鏡め瑾ベ
***@***.***

学生


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IronKinoko/agefans-enhance"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月20日(星期三) 中午12:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IronKinoko/agefans-enhance] 更新请求:  ''次元城动画''网址变更 (Issue #85)





 
更新 v1.43.4 版本

**Comment by 2584191127** [comment]
又变了：https://www.cycani.org/

**Comment by 2584191127** [comment]
最新版本已经支持cycani.org了，但是这里的还是老域名

<img width="76" alt="Image" src="https://github.com/user-attachments/assets/5eb6eae8-8be8-4020-bc80-ac0dbbff06fe" />

**Comment by IronKinoko** [comment]
感谢反馈，确实改漏了

**Comment by Li-lac** [comment]
好像又改了，https://www.ciyuancheng.net/
