### ISSUE TITLE
防止打开 devtools 时自动跳转主页 功能失效

### ISSUE THREAD

**Issue by PYUDNG** [IronKinoko/agefans-enhance#9]
这个功能好像是一直都没有作用的。
打开了devtools访问播放页面会跳转主页
访问播放页面再打开devtools会进入debugger循环

firefox 78.11.0esr (64 位)
Tempermonkey 4.13.6136
（以上均为最新版）

希望作者可以修复。感谢🙏！

**Comment by IronKinoko** [comment]
在首页打开控制台，输入下面这段代码
document.cookie="username=admin; path=/;max-age=9000000"

主要是因为这个会替换掉用户自己的登录状态，所以我就删掉了

**Comment by PYUDNG** [comment]
好的👌谢谢，暂时地解决了。如果能有其他的办法就更好了（替换/拦截掉debugger语句什么的）（强人锁男.psd）
